version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: monthly
    groups:
      prometheus:
        patterns:
          - "github.com/prometheus/*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    groups:
      actions:
        patterns:
          - "actions/*"
